### PR TITLE
Large overhaul for JupyterLab 3.x compatibility

### PR DESCRIPTION
**Pull request by twalcari**
After running into installation problems with the latest versions of JupyterLab (amongst others the problems described in #28), I've done a big overhaul:

1) Created a new integration based on the latest "cookiecutter" template, as described in https://github.com/jupyterlab/extension-examples/tree/master/server-extension

2) Copied over all working pieces from this repository (and it's forks)

3) Integrated and modernized the server-extension from https://github.com/cliffwoolley/jupyter_tensorboard

4) Dropped all changes into this repository in order to create a pull-request

### CODE REVIEW

**Comment by hjalmarlucius** [comment]
Any updates on this? I could not get tb working in jupyter but this patch fixed everything.

**Comment by cliffwoolley** [comment]
@twalcari - Thanks for this!  Is there any benefit to avoiding a (further) fork of jupyter_tensorboard, since technically not everybody uses JupyterLab with TB?  I would be happy to look at merging in your "modernization" changes to https://github.com/cliffwoolley/jupyter_tensorboard -- which we've also considered moving into 
the https://github.com/nvidia/ org since it's gone a few years now without https://github.com/lspvic/jupyter_tensorboard/pull/63 being merged.  If we had a packaged version of the updated jupyter_tensorboard, I think this updated jupyterlab_tensorboard would be able to simply use it by reference the way jupyterlab_tensorboard always has, right?

**Comment by twalcari** [comment]
HI @cliffwoolley . Jupyter Notebook is considered deprecated, which is why I did no effort to keep things compatible with that system. The current setup in which the two plugins depend upon each other has proven to be tedious to get right, which is why I chose to get rid of the dependency in the first place. For me personally, I don't see much value into keeping Jupyter Notebook support around, as all researchers I know have (hapily!) moved on to JupyterLab . If you still want compatibility with both, I think it's perfectly possible to have both in the same plugin.

You're very welcome to take my contribution and merge it into your repo and/or put it on https://github.com/nvidia/ .

Next, we should think about making it installable via `jupyter labextension`. For that we need access to the npmjs package, or create a new one (`jupyterlab-tensorboard` instead of `jupyterlab_tensorboard` ?) I have trouble getting into my account over there as the OTP mails always arrive too late.

**Comment by rvalieris** [comment]
hello, thanks a lot for all the work @twalcari and @cliffwoolley 

I identified an issue with the data ingester, it runs a thread to continuously gather data from the log dir, however when the tensorboard instance is closed the thread still keeps running in the background and printing info() logs every 5s or so.

this is specially annoying on long running jupyterlab instances, every time you start a new tensorboard instance a new ingester thread is created, and they are only stopped when the whole jupyter instance is terminated.

I made a commit that fixes this based on this PR, feel free to use it as it is or re-structure the code in a different way.

https://github.com/rvalieris/jupyterlab_tensorboard/commit/bb30a51372ac9f57cf16280eb63dbe0af0dbe4c9

the main idea of the commit is that a reference of `ingester` needs to be kept, so that when the tensorboard instance is terminated we can set `ingester._reload_interval = 0`  ([see ref](https://github.com/tensorflow/tensorboard/blob/bcd936d70cd51839988c4cc1b72fc5442522a16a/tensorboard/backend/event_processing/data_ingester.py#L113)) effectively terminating the thread.

**Comment by aircloud** [comment]
We also encountered some problems when using jupyterlab-tensorboard before (including [jupyter_tensorboard](https://github.com/lspvic/jupyter_tensorboard), PR but no one responded)

I found that the author of this project has not had an active record on github for more than a year, and may no longer use it, so it is very likely that this pr will be difficult to be merged later.

So in desperation, we re-released a package after fork ourselves（After the release, we found this MR, So I think I can share it here, and I hope to maintain it together with you.）

try:

https://github.com/HFAiLab/jupyterlab_tensorboard_pro

**Comment by chaoleili** [comment]
Hi @twalcari , thanks a lot for your pr, sorry for repling too late due to my personal reason.

**Pull request merged**
